---
name: Lint

on: [pull_request, push]

permissions: read-all

jobs:
  super-lint:
    name: Lint files
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Runs the Super-Linter action
      - name: Run Super-Linter
        uses: github/super-linter/slim@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: devel
          VALIDATE_PYTHON_PYLINT: false
          VALIDATE_GROOVY: false
